name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create zip file
      run: make zip

    - name: Build validation artifact
      run: make validator

    - name: Upload XSD package
      uses: klakegg/github-upload@v0.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "schemas.zip"
        name: "ehf-schemas-${TAG}.zip"
        label: "Package containing XSD files (zip)"

    - name: Upload validation artifact
      uses: klakegg/github-upload@v0.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "target/no.anskaffelser.ehf.schemas-${TAG}.asice"
        label: "Validation artifacts for VEFA Validator 2.x"
        type: "application/vnd.difi.validator.v2+zip"
